### PR TITLE
Push the right state onto the stack

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by Therzok** [comment]
One other option is to not have the thread passed as the parameter, then it should work great.

**Comment by viniciusjarina** [comment]
Good catch! 💯

**Comment by Therzok** [comment]
I think that the Lua.PushThread wihtout a thread parameter works better.

**Comment by viniciusjarina** [comment]
Yeah. Either that or make `PushThread` `static`

**Comment by Therzok** [comment]
That's also an option, but since the API requires you to have the LuaThread, and it's usually self, I'll change it so it doesn't take a parameter. That way you can do:

`new LuaThread().PushThread()`

**Pull request merged**
