### PR TITLE
Add net5.0 test csproj and add it to sln

### PR DESCRIPTION
**Pull request by Therzok**
❓ This uncovers some warnings in using Assembly.CodeBase, that Assembly.Location should be used. Should I fix that too?

### CODE REVIEW

**Comment by viniciusjarina** [comment]
Hi @Therzok that's great! Thank you

Should we also change the pipeline to run those tests on .NET 5 ?

**Review by viniciusjarina — APPROVED** [review]
LGTM, but maybe we can also run the tests on ADO

**Comment by Therzok** [comment]
Added an entry to run the tests. But not sure if I need to add a specific publish task

**Comment by viniciusjarina** [comment]
Perfect!

Merged

**Pull request merged**
